generator:
  class: sfDoctrineGenerator
  param:
    model_class:           peanutPage
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          peanut_page
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
      fields:  ~
      
      list:    
        sort:       [position, asc]
        display:    [title, author, status, position]
      
      filter:
        display:    [title, author, status]
        
      form:    ~
      edit:    ~
      new:     ~
