# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

page:
  url:             /:slug.:sf_format
  class:           sfDoctrineRoute
  options:         { model: peanutPage, type: object }
  param:           { module: page, action: show }
  requirement:     { sf_method: get }

# default rules
homepage:
  url:   /
  param: { module: page, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
