peanutPage:
 actAs:
     Sluggable:
      fields:            [title]
     Timestampable:      ~
     NestedSet:
       hasManyRoots: true
       rootColumnName: root_id
 columns:
     title:              { type: string(255), notnull: true }
     content:            { type: clob, notnull: true }
     excerpt:            { type: clob }
     author:             { type: integer, notnull: true }
     status:             { type: string, notnull: true, values: [draft, publish], default: draft }
 relations:
     sfGuardUser:
      local:             author
      foreign:           id
      foreignAlias:      pageAuthor